# -*- coding: utf-8 -*-
"""
Created on Tue Mar 12 15:34:45 2024

@author: qrb15201
"""

phase_weight = 0.15
apparatus_weight = 0.3
event_weight = 0.4
equipment_weight = 0.05
intended_function_weight = 0.1

class CaseAttributes(Enum):
    
    No = 1
    EquipmentEntity = 2
    Event = 3
    Apparatus = 4
    IntendedFunction = 5
    SubstancePhase = 6
    InferredDeviation = 7
    
    propagation_case_base = [
        # === Pump
        {CaseAttributes.No: 1,
        CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
        CaseAttributes.Event: (effect_onto.PumpRunningDry, event_weight),
        CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
        CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
        CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
        CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature,
        deviation_onto.HighVibration]},
        
        {CaseAttributes.No: 2,
        CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
        CaseAttributes.Event: (causes_onto.EntrainedAir, event_weight),
        CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
        CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
        CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
        CaseAttributes.InferredDeviation: [deviation_onto.NoFlow,
        deviation_onto.LowFlow]},
        
        {CaseAttributes.No: 3,
        CaseAttributes.EquipmentEntity: (equipment_onto.StorageTankEntity, equipment_weight),
        CaseAttributes.Event: (effect_onto.VolumetricDisplacement, event_weight),
        CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
        CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
        CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
        CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        
        {CaseAttributes.No: 4,
        CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
        CaseAttributes.Event: (effect_onto.FluidCirculatesInsidePump, event_weight),
        CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
        CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
        CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
        CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]},
        
        {CaseAttributes.No: 5,
        CaseAttributes.EquipmentEntity: (None, equipment_weight),
        CaseAttributes.Event: (effect_onto.Overfilling, event_weight),
        CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
        CaseAttributes.IntendedFunction: (None, intended_function_weight),
        CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
        CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        
        {CaseAttributes.No: 6,
        CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
        CaseAttributes.Event: (effect_onto.Cavitation, event_weight),
        CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
        CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
        CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
        CaseAttributes.InferredDeviation: [deviation_onto.HighVibration]},
        
        {CaseAttributes.No: 7,
        CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
        CaseAttributes.Event: (causes_onto.DeadHeadingOfPump, event_weight),
        CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
        CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
        CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
        CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        
        {CaseAttributes.No: 8,
         CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 9,
         CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        
        {CaseAttributes.No: 10,
         CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighFlow]},
        
        {CaseAttributes.No: 11,
         CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.OtherThanComposition, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        
        {CaseAttributes.No: 12,
         CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]}, 
    
        {CaseAttributes.No: 13,
         CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        
        {CaseAttributes.No: 14,
         CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowTemperature]},
        
        {CaseAttributes.No: 15,
         CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow, deviation_onto.LowPressure]},
        
        {CaseAttributes.No: 16,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.UnintendedExothermicPolymerization, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature, deviation_onto.HighPressure,
         deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 17,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.UnintendedExothermicPolymerization, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature, deviation_onto.HighPressure,
         deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 18,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.UnintendedExothermicPolymerization, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature, deviation_onto.HighPressure,
         deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 19,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.UnintendedExothermicPolymerization, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature, deviation_onto.HighPressure,
         deviation_onto.NoFlow]},
        # === Overfilling
        {CaseAttributes.No: 20,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.Overfilling, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.ElsewhereFlow]},
        
        {CaseAttributes.No: 21,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.Overfilling, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.ElsewhereFlow]},
        # === ConnectionPipeEntity
        {CaseAttributes.No: 22,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.UnintendedExothermicPolymerization, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 23,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.AbnormalEvaporation, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        
        {CaseAttributes.No: 24,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.AbnormalEvaporation, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        
        {CaseAttributes.No: 25,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.Fracture, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 26,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.Fracture, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 27,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.Fracture, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]}, 
        
        {CaseAttributes.No: 28,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.Fracture, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 29,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (causes_onto.WaterHammer, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighVibration]},
        
        {CaseAttributes.No: 30,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.BrittleFracture, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 31,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.FatigueFracture, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 32,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.Fracture, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        
        {CaseAttributes.No: 33,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.Fracture, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        
        {CaseAttributes.No: 34,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.Fracture, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        
        {CaseAttributes.No: 35,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 36,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 37,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        
        {CaseAttributes.No: 38,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighVibration, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighVibration]},
        
        {CaseAttributes.No: 39,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighVibration, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighVibration]},
        
        {CaseAttributes.No: 40,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighVibration, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighVibration]},
        
        {CaseAttributes.No: 41,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighFlow, deviation_onto.HighVibration]},
        
        {CaseAttributes.No: 42,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighFlow]}, 
        
        {CaseAttributes.No: 43,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighFlow, deviation_onto.HighVibration]},
        
        {CaseAttributes.No: 44,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        
        {CaseAttributes.No: 45,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        
        {CaseAttributes.No: 46,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        
        {CaseAttributes.No: 47,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        
        {CaseAttributes.No: 48,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        
        {CaseAttributes.No: 49,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        
        {CaseAttributes.No: 50,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.OtherThanComposition, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        
        {CaseAttributes.No: 51,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.OtherThanComposition, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        {CaseAttributes.No: 52,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.OtherThanComposition, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        {CaseAttributes.No: 53,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.ReverseFlow]},
        {CaseAttributes.No: 54,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.ReverseFlow]},
        {CaseAttributes.No: 55,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]},
        {CaseAttributes.No: 56,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]},
        {CaseAttributes.No: 57,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]},
        {CaseAttributes.No: 58,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowTemperature]}, 
        
        {CaseAttributes.No: 59,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowTemperature]},
        {CaseAttributes.No: 60,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowTemperature]},
        {CaseAttributes.No: 61,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 62,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 63,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 64,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        {CaseAttributes.No: 65,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 66,
         CaseAttributes.EquipmentEntity: (equipment_onto.ConnectionPipeEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure, deviation_onto.LowFlow]},
        # === Pressure vessel
        {CaseAttributes.No: 67,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.IncompleteEvaporation, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Evaporation, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        {CaseAttributes.No: 68,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.AbnormalEvaporation, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 69,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.AbnormalEvaporation, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 70,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.HeatBuildUp, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 71,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.HeatBuildUp, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 72,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.AbnormalEvaporation, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        # {CaseAttributes.No: 73,
        # CaseAttributes.EquipmentEntity: (None, equipment_weight),
        # CaseAttributes.Event: (effect_onto.PressureSurge, event_weight),
        # CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
        # CaseAttributes.IntendedFunction: (None, intended_function_weight),
        # CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
        # CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 74,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.AbnormalEvaporation, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]}, 
        
        # === Vacuum formation
        {CaseAttributes.No: 75,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 76,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        # === Internal Leakage
        {CaseAttributes.No: 77,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (causes_onto.InternalLeakage, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        # == Fracture -> Low level, nicht relevant, since leakage is relevant in case of a Fracture
        {CaseAttributes.No: 78,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 79,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        # == Low pressure in Tank
        {CaseAttributes.No: 80,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 81,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 82,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        {CaseAttributes.No: 83,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        {CaseAttributes.No: 84,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        {CaseAttributes.No: 85,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        {CaseAttributes.No: 86,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        {CaseAttributes.No: 87,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowLevel, event_weight),
         CaseAttributes.Apparatus: (None, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        {CaseAttributes.No: 88,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 89,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 90,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]}, 
        
        {CaseAttributes.No: 91,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 92,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 93,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 94,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 95,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 96,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 97,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 98,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 99,
         CaseAttributes.EquipmentEntity:    (None, equipment_weight),
         CaseAttributes.Event:              (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus:          (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction:   (None, intended_function_weight),
         CaseAttributes.SubstancePhase:     (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 100,
         CaseAttributes.EquipmentEntity:    (None, equipment_weight),
         CaseAttributes.Event:              (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus:          (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction:   (None, intended_function_weight),
         CaseAttributes.SubstancePhase:     (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 101,
         CaseAttributes.EquipmentEntity:    (None, equipment_weight),
         CaseAttributes.Event:              (deviation_onto.OtherThanComposition, event_weight),
         CaseAttributes.Apparatus:          (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction:   (None, intended_function_weight),
         CaseAttributes.SubstancePhase:     (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        {CaseAttributes.No: 102,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.OtherThanComposition, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        # === Compressor
        {CaseAttributes.No: 103,
         CaseAttributes.EquipmentEntity: (equipment_onto.CompressorEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.CompressorCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow, deviation_onto.LowPressure]},
        {CaseAttributes.No: 104,
         CaseAttributes.EquipmentEntity: (equipment_onto.CompressorEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.CompressorCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowTemperature]},
        {CaseAttributes.No: 105,
         CaseAttributes.EquipmentEntity: (equipment_onto.CompressorEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.CompressorCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]},
        {CaseAttributes.No: 106,
         CaseAttributes.EquipmentEntity: (equipment_onto.CompressorEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.CompressorCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowTemperature]},#]}, 
            
            
        {CaseAttributes.No: 107,
         CaseAttributes.EquipmentEntity: (equipment_onto.CompressorEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.CompressorCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow, deviation_onto.LowPressure]},
        {CaseAttributes.No: 108,
         CaseAttributes.EquipmentEntity: (equipment_onto.CompressorEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.CompressorCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow, deviation_onto.LowPressure]},
        {CaseAttributes.No: 109,
         CaseAttributes.EquipmentEntity: (equipment_onto.CompressorEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.CompressorCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        # === Valve
        {CaseAttributes.No: 110,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.Cavitation, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighVibration]},
        # {CaseAttributes.No: 111,
        # CaseAttributes.EquipmentEntity: (None, equipment_weight),
        # CaseAttributes.Event: (effect_onto.PressureSurge, event_weight),
        # CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
        # CaseAttributes.IntendedFunction: (None, intended_function_weight),
        # CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
        # CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 112,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.Cavitation, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighVibration]},
        {CaseAttributes.No: 113,
         CaseAttributes.EquipmentEntity: (equipment_onto.AirCooledCondenserEntity, equipment_weight),
         CaseAttributes.Event: (causes_onto.NonCondensables, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Casing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Condensation, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 114,
         CaseAttributes.EquipmentEntity: (equipment_onto.PumpEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.UnintendedExothermicPolymerization, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PumpCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Transport, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        # === Compressor
        {CaseAttributes.No: 115,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.ExcessiveDischargeTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.CompressorCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]},
        {CaseAttributes.No: 116,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.IncreasedOilDischarge, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.CompressorCasing, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.MaterialTransfer, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]},
        # === Dev to Dev Cases========================================================
        {CaseAttributes.No: 117,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowTemperature]},
        {CaseAttributes.No: 118,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowTemperature]},
        {CaseAttributes.No: 119,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowTemperature]},
        {CaseAttributes.No: 120,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]},
        {CaseAttributes.No: 121,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]},
            
        {CaseAttributes.No: 122,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighTemperature]},
        {CaseAttributes.No: 123,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        {CaseAttributes.No: 124,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        {CaseAttributes.No: 125,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        {CaseAttributes.No: 126,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 127,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 128,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 129,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighFlow]},
        {CaseAttributes.No: 130,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighFlow]},
        {CaseAttributes.No: 131,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighFlow]},
        {CaseAttributes.No: 132,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 133,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 134,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowPressure, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 135,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        {CaseAttributes.No: 136,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        
        {CaseAttributes.No: 137,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        {CaseAttributes.No: 138,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighVibration, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighVibration]},
        {CaseAttributes.No: 139,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighVibration, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighVibration]},
        {CaseAttributes.No: 140,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighVibration, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighVibration]},
        {CaseAttributes.No: 141,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.OtherThanComposition, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        {CaseAttributes.No: 142,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.OtherThanComposition, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        {CaseAttributes.No: 143,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.OtherThanComposition, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        {CaseAttributes.No: 144,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 145,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        {CaseAttributes.No: 146,
         CaseAttributes.EquipmentEntity: (equipment_onto.ValveEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.Body, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow, deviation_onto.LowPressure]},
        {CaseAttributes.No: 147,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 148,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 149,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 150,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 151,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.ElsewhereFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 152,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]}, 
        
        {CaseAttributes.No: 153,
         CaseAttributes.EquipmentEntity: (equipment_onto.StorageTankEntity, equipment_weight),
         CaseAttributes.Event: (effect_onto.AbnormalEvaporation, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 154,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 155,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 156,
         CaseAttributes.EquipmentEntity: (equipment_onto.InertgasBlanketingEntity, equipment_weight),
         CaseAttributes.Event: (causes_onto.IncreasedInletPressure, event_weight),
         CaseAttributes.IntendedFunction: (process_onto.Inertization, intended_function_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 157,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 158,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 159,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 160,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighTemperature, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 161,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighLevel]},
        {CaseAttributes.No: 162,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighLevel]},
        {CaseAttributes.No: 163,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighLevel]},
        {CaseAttributes.No: 164,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 165,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 166,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 167,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 168,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        
        
        {CaseAttributes.No: 169,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 170,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 171,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighLevel, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        # === Source
        {CaseAttributes.No: 172,
         CaseAttributes.EquipmentEntity: (equipment_onto.SourceEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (None, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.NoFlow]},
        {CaseAttributes.No: 173,
         CaseAttributes.EquipmentEntity: (equipment_onto.SourceEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (None, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowFlow]},
        {CaseAttributes.No: 174,
         CaseAttributes.EquipmentEntity: (equipment_onto.SourceEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (None, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighFlow]},
        {CaseAttributes.No: 175,
         CaseAttributes.EquipmentEntity: (equipment_onto.SourceEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.OtherThanComposition, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (None, intended_function_weight),
         CaseAttributes.SubstancePhase: (None, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]},
        # === Settling tank
        {CaseAttributes.No: 176,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.BacteriaGrowth, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighCorrosion]},
        {CaseAttributes.No: 177,
         CaseAttributes.EquipmentEntity: (equipment_onto.SettlingTankEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.LowFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Separation, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 178,
         CaseAttributes.EquipmentEntity: (equipment_onto.SettlingTankEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Separation, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowLevel]},
        {CaseAttributes.No: 179,
         CaseAttributes.EquipmentEntity: (equipment_onto.SettlingTankEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Separation, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Liquid, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighLevel, deviation_onto.HighFlow]},
        {CaseAttributes.No: 180,
         CaseAttributes.EquipmentEntity: (equipment_onto.SettlingTankEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Separation, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighLevel, deviation_onto.HighFlow]},
        # === Inertgas blanketing unit
        {CaseAttributes.No: 181,
         CaseAttributes.EquipmentEntity: (equipment_onto.InertgasBlanketingEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.NoFlow, event_weight),
         CaseAttributes.IntendedFunction: (process_onto.Inertization, intended_function_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.LowPressure]},
        {CaseAttributes.No: 182,
         CaseAttributes.EquipmentEntity: (equipment_onto.InertgasBlanketingEntity, equipment_weight),
         CaseAttributes.Event: (deviation_onto.HighFlow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.NoApparatus, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Inertization, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Gaseous, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighPressure]},
        {CaseAttributes.No: 183,
         CaseAttributes.EquipmentEntity: (None, equipment_weight),
         CaseAttributes.Event: (effect_onto.BacteriaGrowth, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.AtmosphericStorageTank, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Storage, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.HighCorrosion]},
        {CaseAttributes.No: 184,
         CaseAttributes.EquipmentEntity: (equipment_onto.SettlingTankEntity, equipment_weight),
         CaseAttributes.Event: (causes_onto.ExcessiveInflow, event_weight),
         CaseAttributes.Apparatus: (equipment_onto.PressureVessel, apparatus_weight),
         CaseAttributes.IntendedFunction: (process_onto.Separation, intended_function_weight),
         CaseAttributes.SubstancePhase: (substance_onto.Multiphase, phase_weight),
         CaseAttributes.InferredDeviation: [deviation_onto.OtherThanComposition]}, 
    ] 
    
    def calculate_similarity(new_case, old_case):
        
        if new_case is None or old_case is None:
            print("Similarity could not be calculated because of None")
            return 0
        else:
            attr_list = [   CaseAttributes.EquipmentEntity,
                            CaseAttributes.Event,
                            CaseAttributes.Apparatus,
                            CaseAttributes.IntendedFunction,
                            CaseAttributes.SubstancePhase
                        ]
            similarities = []
            weights = []
            sum_of_weights = 0
            for attr in attr_list:
                if old_case.get(attr)[0]:
                    similarities.append(similar(new_case.get(attr), old_case.get(attr)[0]))
                else:
                    similarities.append(0)
                    weights.append(old_case.get(attr)[1])
                    sum_of_weights += old_case.get(attr)[1]
            similarity_products = [a * b for a, b in zip(similarities, weights)]
            sum_ = sum(similarity_products)
            # Overall similarity
            similarity = 1 / sum_of_weights * sum_
            
            return similarity
    
    def match_case_with_cb(current_case, case_base):
        list_similarities = []
        
        for case in case_base:
            list_similarities.append((calculate_similarity(current_case, case), case.get(CaseAttributes.InferredDeviation)))

        res_list = [x[0] for x in list_similarities]
        max_similarity_measure = max(res_list)
        
        if max_similarity_measure >= 0.75:
            index = res_list.index(max_similarity_measure)
            relevant_deviation = list_similarities[index][1]
        else:
            relevant_deviation = None
            
        return relevant_deviation





